# Global configuration
data:
  raw_path: data/raw/loan_data.csv
  processed_path: data/processed/clean_loan_data.csv
model:
  save_dir: models
  target: Loan_Status
evaluation:
  cv_folds: 5
  primary_metric: f1
